sudo: 'required'

services:
  - 'docker'

env:
  - DOCKER_REPO='timmclifford' BUILD_NUMBER='1' GIT_BRANCH=master

before_install:
  - './.travis/main.sh'

script:
  - 'make build'
  - 'make test'

after_success:
  - echo $TRAVIS_BRANCH
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && docker tag $DOCKER_REPO:buildtag_$BUILD_NUMBER $DOCKER_REPO:latest && docker push $DOCKER_REPO:latest; \
    fi

notifications:
  email: false
