sudo: 'required'

services:
  - 'docker'

env:
  - DOCKER_REPO='timmclifford' BUILD_NUMBER='1' GIT_BRANCH=master

before_install:
  - './.travis/main.sh'

script:
  - 'make build'
  - 'make test'

after_success:
  - echo $TRAVIS_BRANCH
  - if [ "$TRAVIS_BRANCH" == "master" ]; then docker login -u $DOCKER_USERNAME --password $DOCKER_PASSWORD; docker push $DOCKER_REPO/cypress_base:$TRAVIS_BUILD_NUMBER; fi

notifications:
  email: false
