sudo: 'required'

services:
  - 'docker'

env:
  - DOCKER_REPO='timmclifford'
  - BUILD_NUMBER='1'
  - GIT_BRANCH=master

before_install:
  - './.travis/main.sh'

script:
  - 'make build'
  - 'make test'

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && make publish_images && make remove
    fi

notifications:
  email: false
